version: '3.3'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5433:5433
    volumes:
      - ~/apps/tp_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=tp_password
      - POSTGRES_USER=tp_user
      - POSTGRES_DB=tp_db
